# Generated by Django 4.2.6 on 2023-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Question Text')),
                ('pub_date', models.DateTimeField(verbose_name='Publication Date')),
            ],
        ),
    ]
